apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: demo-client
  namespace: platform-kafka
  labels:
    strimzi.io/cluster: platform-kafka
spec:
  authentication:
    type: tls

  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: platform-events
          patternType: literal
        operations:
          - Read
          - Write
          - Describe

      - resource:
          type: group
          name: demo-client
          patternType: literal
        operations:
          - Read

      - resource:
          type: cluster
        operations:
          - IdempotentWrite
