apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: strimzi-operator
  namespace: argocd
spec:
  description: GitOps project for the Strimzi Cluster Operator

  sourceRepos:
    - https://strimzi.io/charts/

  destinations:
    - namespace: platform-kafka
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
      name: platform-kafka
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: ServiceAccount
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: apps
      kind: Deployment
